Our objective in this lab is to understand the Python toolkit available to us for Data Analytics activities. The two libraries we are going to focus on are:



*   NumPy
*   Pandas



Let's first import numpy.

In [1]:
import numpy as np

Define a Python list containing the ages of 6 customers.

In [2]:
ages = [40, 35, 18, 32, 65, 43]
print(ages)

[40, 35, 18, 32, 65, 43]


How do we instantiate a Numpy ndarray object? HINT: using `np.array(<collection>)`

In [3]:
ages = np.array(ages)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[40 35 18 32 65 43]


Size helps us finds the number of elements, while the shape describes the layout of the data. For example, if we have a 2X2 matrix, the size would be 4 while shape would be (2,2)

In [4]:
names=['Bob', 'Tim', 'Arshad', 'Joanna', 'Michelle','Mo']
customers = np.array([names, ages])
print("Size:\t" , customers.size)
print("Shape:\t", customers.shape)

Size:	 12
Shape:	 (2, 6)


Numpy can also generate an array containing all 0s! Why would we have such a thing? Well, it helps in counters and in machine learning activities.

In [5]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


You can change the shape of the data and its layout, using the reshape function.

In [6]:
#Let's reshape the array:
people = customers.reshape(4,3)



Now print the size and shape again. 
###### Note: The new shape must be the same "size" as the old shape

In [7]:
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [['Bob' 'Tim' 'Arshad']
 ['Joanna' 'Michelle' 'Mo']
 ['40' '35' '18']
 ['32' '65' '43']]
Size:	 12
Shape:	 (4, 3)


Instead of defining an array manually, create an array with numpy.

HINT: The `np.arange()` method creates a range of numbers with user defined steps between each.

In [8]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Let's try out operations on arrays. Below, we have an array by name 'table'.

In [9]:
table= np.arange(0, 55, 5)

In [10]:
#Print the multiplication of 2 on table array.
print("1:", 2 * table)
#Print the addition of 10 to table array.
print("2:", 10 + table)
#Print the subtraction of 1 from table array.
print("3:", table - 1)
#Print the division of 5 with table array.
print("4:", table/5)
#Print the square of table array.
print("5:", table **2)
#Print true if the element is greater than 10.
print("6:", table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


Sometimes the data is not readble as-it-is. For example, due to human/tool error, we may read numbers as strings.

What is the data type of the below ndarray?

In [11]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

#answer
ages_with_strings.dtype

dtype('<U21')

What is the dtype of this array?

In [12]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

#answer
ages_with_strings.dtype

dtype('int32')

We have an array named ops, Lets perform operations on it.

In [13]:
ops= np.arange(0, 55, 5)
print(ops)

[ 0  5 10 15 20 25 30 35 40 45 50]


Print the first 4 element of the array

In [14]:
ops[:4]

array([ 0,  5, 10, 15])

Print everything but the first 4 element of the array

In [15]:
ops[4:]

array([20, 25, 30, 35, 40, 45, 50])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [16]:
print(people)
print('********')
print(people[-1:, :2])

[['Bob' 'Tim' 'Arshad']
 ['Joanna' 'Michelle' 'Mo']
 ['40' '35' '18']
 ['32' '65' '43']]
********
[['32' '65']]


Numpy also supports rounding off

In [17]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

Let's work on statistics now. We have an array 'numbers'

In [18]:
numbers = np.arange(0, 4, 0.2555)

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [19]:
print("min = ", np.min(numbers).round(2))
print("max = ", np.max(numbers).round(2))
print("sum = ", np.sum(numbers).round(2))
print("mean = ", np.mean(numbers).round(2))
print("median = ", np.median(numbers).round(2))
print("var = ", np.var(numbers).round(2))
print("std = ", np.std(numbers).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


## Random

Randomness helps with probability and generating seeds for encryptions. Assume you flip a coin 10 times- each time you could recieve tail (0) or head (1).

In [20]:
flip = np.random.choice([0,1], 10)
flip

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1])

We can quickly generate multi-dimensional random numbers!

In [21]:
np.random.rand(4,3,2)

array([[[0.77237975, 0.95850579],
        [0.76126618, 0.62520276],
        [0.99827949, 0.81046051]],

       [[0.29554283, 0.29378864],
        [0.46415235, 0.4869662 ],
        [0.55486017, 0.11448782]],

       [[0.17999812, 0.13295701],
        [0.49194878, 0.44774085],
        [0.76940284, 0.61425534]],

       [[0.36202266, 0.42986747],
        [0.98922656, 0.26115411],
        [0.81097856, 0.65234085]]])

Produce 1000 datapoints of a normally distributed data set.

HINT: `np.random.normal()`

In [22]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

In [23]:
import pandas as pd



In [24]:
path = 'chipotle.tsv'

chipo = pd.read_csv(path, sep = '\t')
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Business Query: How many 1-item orders cost more than $10.00?

In [25]:
# clean the item_price column and transform it in a float
prices = [float(value[1 : -1]) for value in chipo.item_price]

# reassign the column with the cleaned prices
chipo.item_price = prices


In [26]:
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98

In [27]:

# delete the duplicates in item_name and quantity
chipo_filtered = chipo.drop_duplicates(['item_name','quantity','choice_description'])

# select only the products with quantity equals to 1
chipo_one_prod = chipo_filtered[chipo_filtered.quantity == 1]
chipo_one_prod

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
5            3         1                           Chicken Bowl   
...        ...       ...                                    ...   
4602      1827         1                       Barbacoa Burrito   
4607      1829         1                          Steak Burrito   
4610      1830         1                          Steak Burrito   
4611      1830         1                         Veggie Burrito   
4612      1831         1                          Carnitas Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]        3.39  
2                                               [Apple]        3.39  
3                                                   NaN        2.39  
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
...                                                 ...         ...  
4602                      [Tomatillo Green Chili Salsa]        9.25  
4607  [Tomatillo Green Chili Salsa, [Rice, Cheese, S...       11.75  
4610  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4611  [Tomatillo Green Chili Salsa, [Rice, Fajita Ve...       11.25  
4612  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...        9.25  

[1806 rows x 5 columns]

In [28]:

chipo_one_prod.query('item_price > 10').item_name.nunique()

25

What is the average price of each item? 
###### HINT: print a data frame with only two columns item_name and item_price

In [29]:

# select only the item_name and item_price columns
price_per_item = chipo_one_prod[['item_name', 'item_price']]

# perform a grouping along the item names
price_per_item = price_per_item.groupby(['item_name'], sort=True)['item_price'].mean()

price_per_item.head(10)

item_name
6 Pack Soft Drink         6.490000
Barbacoa Bowl            10.227959
Barbacoa Burrito          9.979577
Barbacoa Crispy Tacos    10.171000
Barbacoa Salad Bowl      10.778889
Barbacoa Soft Tacos      10.380000
Bottled Water             1.090000
Bowl                      7.400000
Burrito                   7.400000
Canned Soda               1.090000
Name: item_price, dtype: float64

Sort by the name of the item

In [30]:
chipo.item_name.sort_values()

# OR

chipo.sort_values(by = "item_name")

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
...        ...       ...                ...   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
...                                                 ...         ...  
2384  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        8.75  
781   [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...        8.75  
2851  [Roasted Chili Corn Salsa (Medium), [Black Bea...        8.49  
1699  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25  
1395  [Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...        8.49  

[4622 rows x 5 columns]

What was the quantity of the most expensive item ordered?

In [31]:
chipo.sort_values(by = "item_price", ascending = False).head(1)

order_id  quantity                     item_name choice_description  \
3598      1443        15  Chips and Fresh Tomato Salsa                NaN   

      item_price  
3598       44.25

How many times was a Veggie Salad Bowl ordered?

In [32]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

len(chipo_salad)

18

How many times did someone order more than one Canned Soda?

In [33]:
chipo_drink_steak_bowl = chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]
len(chipo_drink_steak_bowl)

20

Phew! There are so many functions in pandas and numpy! But they make our life easy. We can get a full list of available functions using dir command

In [34]:
print(dir(pd.DataFrame))

['T', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '_

In [35]:
# we can filter this data to get all useful function
all_panda_fns = dir(pd.DataFrame)
without_ = lambda fnname: fnname if '_' not in fnname else None
clean_names = [ without_(fn) for fn in all_panda_fns]
clean_names = list(filter(None, clean_names))

In [36]:
print(clean_names)

['T', 'abs', 'add', 'agg', 'aggregate', 'align', 'all', 'any', 'append', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'attrs', 'axes', 'backfill', 'bfill', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'compare', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'info', 'insert', 'interpolate', 'isin', 'isna', 'isnull', 'items', 'iteritems', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'le', 'loc', 'lookup', 'lt', 'mad', 'mask', 'max', 'mean', 'median', 'melt', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pipe', 'piv

There are lot of special functions in pandas- like describe

In [37]:
chipo.describe()

order_id     quantity   item_price
count  4622.000000  4622.000000  4622.000000
mean    927.254868     1.075725     7.464336
std     528.890796     0.410186     4.245557
min       1.000000     1.000000     1.090000
25%     477.250000     1.000000     3.390000
50%     926.000000     1.000000     8.750000
75%    1393.000000     1.000000     9.250000
max    1834.000000    15.000000    44.250000

We can take a 'Transpose' of our matrix to make it easier to read the specific stats.

In [38]:
chipo.describe().T

count        mean         std   min     25%     50%      75%  \
order_id    4622.0  927.254868  528.890796  1.00  477.25  926.00  1393.00   
quantity    4622.0    1.075725    0.410186  1.00    1.00    1.00     1.00   
item_price  4622.0    7.464336    4.245557  1.09    3.39    8.75     9.25   

                max  
order_id    1834.00  
quantity      15.00  
item_price    44.25

For instance, selecting mean of all the columns becomes easier.

In [39]:
chipo.describe().T['mean']

order_id      927.254868
quantity        1.075725
item_price      7.464336
Name: mean, dtype: float64

Pandas can also help us slice-and-dice the data with help of LOC and ILOC functions.

In [40]:
# loc filters by location name
chipo.loc[:5, ['order_id','quantity']]

order_id  quantity
0         1         1
1         1         1
2         1         1
3         1         1
4         2         2
5         3         1

In [41]:
# iloc filters by index of the location
chipo.iloc[:5 , :2]

order_id  quantity
0         1         1
1         1         1
2         1         1
3         1         1
4         2         2

Observe how in iloc we have values excluding our limit, while in loc including our limit.